[project]
name = "torchless-xor"
version = "0.1.0"
description = "Contains simple implementations of NN components and their derivations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
]
